version: '3.9'
services:
  thom-app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 1234:1234
    command: pnpm run dev
  thom-auth:
    image: thomasnewman/thom-auth:0.0.3
    env_file:
      - .env
    ports:
      - 3001:3001
    environment:
      - CORS_ORIGIN=http://localhost:1234
      - MONGO_HOST=mongo-auth
      - SEED=true
    restart: on-failure
  mongo-auth:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
