version: '3'
services:
  thom-auth:
    image: thom-auth
    ports:
      - '3001:3001'
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongo-auth
      - SEED=true
    depends_on:
      - 'mongo-auth' # this doesn;t work enough, container needs a restart with docker restart <container_id>
  mongo-auth:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    # expose:
    #   - 27017
    ports:
      - '27017:27017'
